arjoonn/arjoonn/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
	url(r'^admin/', include(admin.site.urls)),
	url(r'^',include('mainsite.urls',namespace='mainsite-urls',app_name='mainsite')),
	url(r'^contact/',include('contact.urls',namespace='contact-urls',app_name='contact')),
)

arjoonn/contact/urls.py
from django.conf.urls import patterns,url
from contact import views
urlpatterns=patterns('',
	url('^$',views.home,name='home'),
	url('^success/$',views.success,name='success'),
	url('^fail/$',views.fail,name='fail'),
)

arjoonn/mainsite/urls.py
from django.conf.urls import patterns,url

urlpatterns=patterns('mainsite.views',
	url(r'^$','home',name='home'),
	url(r'^about/$','about',name='about'),
	url(r'^workflow/$','workflow',name='workflow'),
	url(r'^team/$','team',name='team'),
	url(r'^track/$','track',name='track'),
)

arjoonn/contact/models.py
from django import forms
from django.db import models

class message(models.Model):
	"To hold a message"
	def __unicode__(self):
		return str(self.name)
	name=models.CharField(max_length=50)
	email=models.EmailField(help_text='Where can i get back to you?')
	message=models.TextField()
	read=models.BooleanField(default=False)
	stamp=models.DateTimeField(auto_now_add=True)

#---------------FORMS---------------
class MessageForm(forms.ModelForm):
	class Meta:
		model=message
		exclude=['read','stamp']

arjoonn/contract/models.py
from django.db import models

def contract(models.Model):
	"contract for a job information"
	

arjoonn/control/models.py
from django.db import models

class variable(models.Model):
	"Control variables for various applications in the project"
	def __unicode__(self):
		return str(self.name)
	appname=models.CharField(max_length=50)
	name=models.CharField(max_length=50)
	value=models.CharField(max_length=100,blank=True)
	file_attached=models.FileField(upload_to='control/files',blank=True,null=True,default=None)

arjoonn/mainsite/models.py
from django.db import models

arjoonn/contact/views.py
from django.shortcuts import render,redirect
import control,contact
#-----------------------------------
def home(request):
	"homepage of contact form"
	data={}
	template='contact/home.html'
	if request.method=='GET':
		data['form']=contact.models.MessageForm()
	if request.method=='POST':
		try:
			form=contact.models.MessageForm(request.POST)
			if form.is_valid():
				form.save()
				return redirect('contact:success')
			else:
				data['form']=form
		except Exception as e:
			print e
			return redirect('contact:fail')
	return render(request,template,data)
def success(request):
	"Successfully submitted form"
	data={}
	template='contact/success.html'
	data['form']=contact.models.MessageForm()
	return render(request,template,data)
def fail(request):
	"Failed in the  submitted form"
	data={}
	template='contact/fail.html'
	data['form']=contact.models.MessageForm()
	return render(request,template,data)

arjoonn/contract/views.py
from django.shortcuts import render

# Create your views here.

arjoonn/control/views.py
from django.shortcuts import render

# Create your views here.

arjoonn/mainsite/views.py
from django.shortcuts import render




def home(request):
	"Site homepage"
	data={}
	template='mainsite/home.html'
	return render(request,template,data)
def about(request):
	"About our work"
	data={}
	template='mainsite/about.html'
	return render(request,template,data)
def workflow(request):
	"About our work"
	data={}
	template='mainsite/workflow.html'
	return render(request,template,data)
	
def team(request):
	"About our work"
	data={}
	template='mainsite/team.html'
	return render(request,template,data)

def track(request):
	"My past and current works"
	data={}
	template="mainsite/works.html"
	return render(request,template,data)

arjoonn/contact/templates/contact/fail.html
{%extends 'contact/home.html'%}
{%block contactbody%}
	<div class='container'>
		It seems something went wrong. I have taken note of it.<br>
		Please try later or you can try my email too.<br>
	</div>
{%endblock%}

arjoonn/contact/templates/contact/home.html
{%extends 'base.html'%}
{%block head%}
{% load crispy_forms_tags %}
{%endblock%}

{%block body%}
	<div class='container-fluid'>
		<p class='lead text-justify'>
			You can contact me via this form.Or you can reach me via email at:<br>
			<a href='mailto:perfect.circle.arjoonn@gmail.com'>perfect.circle.arjoonn@gmail.com</a>
		</p>
	</div>
	<div class='container col-md-4'>
		<form class='form' action={%url 'contact:home'%} method='post'>
			{%csrf_token%}
			{{form|crispy}}
			<div class='control-group'>
				<div class='controls'>
				<input class='btn btn-primary' type='submit' value='Send'/>
				</div>
			</div>
		</form>
	</div>
	{%block contactbody%}
	{%endblock%}
{%endblock%}

arjoonn/contact/templates/contact/success.html
{%extends 'contact/home.html'%}
{%block contactbody%}
	<div class='container'>
		The message has been sent. I usually read them in the evenings so please be patient.<br>
		Thanks for taking interest.
		
	</div>
{%endblock%}

arjoonn/mainsite/templates/mainsite/about.html
{%extends 'base.html'%}

{%block head%}
{%endblock%}

{%block body%}
	<div role="tabpanel">

	  <!-- Nav tabs -->
	  <ul class="nav nav-tabs" role="tablist">
	    <li role="presentation" class="active"><a href="#Who" aria-controls="Who" role="tab" data-toggle="tab">Who are we?</a></li>
	    <li role="presentation"><a href="#What" aria-controls="What" role="tab" data-toggle="tab">What do we do?</a></li>
	    <li role="presentation"><a href="#Charges" aria-controls="Charges" role="tab" data-toggle="tab">What do we charge?</a></li>
	    <li role="presentation"><a href="#Hire" aria-controls="Hire" role="tab" data-toggle="tab">Hire Us!</a></li>
	  </ul>

	  <!-- Tab panes -->
	  <div class="tab-content">
	    <div role="tabpanel" class="tab-pane active" id="Who">
	    	<p>
			We are a close knit group of people who love the internet.
			Most of us graduated from St. Stephen's College, University of Delhi.
			All of us are addicted to programming and design.
		</p>
	    </div>
	    <div role="tabpanel" class="tab-pane" id="What">
	    	<p>
			We build websites in the fastest time you have seen.
			The current record stands at 3 hours 55 minutes.
			We also maintain them at blazing speeds. Within 3 hours of a client telling
			us to update something the task is done.
			This is possible only because we sleep only an hour each. :-)
			In our office constant programming is always happening	
		</p>
	    </div>
	    <div role="tabpanel" class="tab-pane" id="Charges">
	    	<p>
			Since we are driven primarily by passion we chare you only for maintaining te site
			and our daily bread. Thus we exit only to make websites. We have a few prebuilt
			packages you can choose from. If none of them fit your needs contact us and we will
			figure something out.
		</p>
	    </div>
	    <div role="tabpanel" class="tab-pane" id="Hire">
	    	<p>
			Take your time and look at the market of web developers.
			Sure there are better ones,cheaper ones but the work we do, at the 
			speed and price we do it is unmatched. This is only possible because we 
			love this job.
		
			Here is what our contract generally looks like. Of course if you hire us 
			it will be tailored to the situation and your needs. This is a simple
			guideline.
		</p>
	    </div>
	  </div>

	</div>
	
{%endblock%}

arjoonn/mainsite/templates/mainsite/home.html
{%extends 'base.html'%}
{%block head%}
	{%load staticfiles%}
	<script src='https://apis.google.com/js/platform.js' async defer></script>

{%endblock%}

{%block body%}
<!--Facebook like button-->
	<div id="fb-root"></div>
		<script>(function(d, s, id) {var js, fjs = d.getElementsByTagName(s)[0];if (d.getElementById(id)) return;js = d.createElement(s); js.id = id;js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.0";fjs.parentNode.insertBefore(js, fjs);}(document, 'script', 'facebook-jssdk'));</script>
	<!--Facebook like button JS done-->


	<div class='container-fluid'><div class='row'>
		<div class='col-md-8'>
			<div class='row'>
				<img class='img-responsive img-circle img-border col-md-2' src={%static 'profile_picture.jpg'%} alt='Profile_picture'/>
				<div class='col-md-2'>
					<!--Google plus-->
						<div class='g-plusone'></div>
					<!--Twitter-->
						<a href="https://twitter.com/share" class="twitter-share-button" data-hashtags="a">Tweet</a><script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
					<!--Github-->
						<iframe src="http://ghbtns.com/github-btn.html?user=theSage21&repo=jarvis&count=true&type=follow"allowtransparency="true" frameborder="0" scrolling="0" width="165" height="20"></iframe>
					<!--Facebook-->
						<div class="fb-like" data-href="https://www.facebook.com/arjoonn" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>
				</div>
			</div>
			<div class='row'>
				<div class='col-md-8'>
					<p class='lead'>Websites.Fast.</p>
					<blockquote class='bold'>
					<p>
						With Perfect Circle you will experience the fastest development and maintainence in the business.
						To be honest we are available 23x7. We sleep for an hour everyday :-)
					</p>
					<footer>Arjoonn Sharma</footer>
					</blockquote>
				</div>
			</div>
		</div>
	</div></div>
{%endblock%}

arjoonn/mainsite/templates/mainsite/team.html
{%extends 'base.html'%}

{%block body%}
	
{%endblock%}

arjoonn/mainsite/templates/mainsite/workflow.html
{%extends 'base.html'%}

{%block body%}
	
{%endblock%}

arjoonn/mainsite/templates/mainsite/works.html
{%extends 'base.html'%}

{%block body%}
	
{%endblock%}

arjoonn/templates/base.html
<!DOCTYPE html>

<html lang='en'>
	<head>
		{%load staticfiles%}
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="{%static 'boot/css/bootstrap.min.css'%}">
		
		<title>
			Arjoonn Sharma
		</title>
		<style>
			body{
				background:url('{%static "background.jpg"%}');
				background-size:800px 800px;
				background-repeat:repeat;
				}
		</style>
		{%block head%}
		{%endblock%}
		
	</head>
	
	<body>
		<nav class="navbar navbar-inverse" role="navigation">
			<div class="container-fluid">
				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="{%url 'mainsite-urls:home'%}">
						<span class="glyphicon glyphicon-record"></span>
						Perfect Circle
					</a>
				</div>
					
				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class='collapse navbar-collapse' id='bs-example-navbar-collapse-1'>
					<ul class="nav navbar-nav">
						<li><a href={%url 'mainsite-urls:home'%}>Homepage</a></li>
						<li><a href={%url 'mainsite-urls:workflow'%}>Workflow</a></li>
						<li><a href={%url 'mainsite-urls:team'%}>Our team</a></li>
						<li><a href={%url 'mainsite-urls:about'%}>About</a></li>
						<li><a href={%url 'contact-urls:home'%}>Contact</a></li>
					</ul>
				</div>



			</div>
		</nav>		



		<div class='container-fluid text-left'>
		{%block body%}
		{%endblock%}
		</div>
		
		<!-- scripts placed here to speed up the page load time-->
		<script src="{%static 'jquery.js'%}"></script>
		<script src="{%static 'boot/js/bootstrap.min.js'%}"></script>

	</body>

</html>